/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * client API
 * OpenAPI spec version: 0.1.0
 */
import type { AppSchemasClientLevelLevelOutIsLocked } from './appSchemasClientLevelLevelOutIsLocked';

export interface AppSchemasClientLevelLevelOut {
  id: number;
  name: string;
  alias: string;
  value: number;
  isLocked?: AppSchemasClientLevelLevelOutIsLocked;
}
