/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * client API
 * OpenAPI spec version: 0.1.0
 */
import type { AssetStatus } from './assetStatus';
import type { AssetOutWidth } from './assetOutWidth';
import type { AssetOutHeight } from './assetOutHeight';

export interface AssetOut {
  id: number;
  status: AssetStatus;
  mimeType: string;
  sizeBytes: number;
  width?: AssetOutWidth;
  height?: AssetOutHeight;
  fileKey: string;
  imageUrl: string;
  createdAt: string;
  updatedAt: string;
}
