/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * client API
 * OpenAPI spec version: 0.1.0
 */

export type AssetStatus = typeof AssetStatus[keyof typeof AssetStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AssetStatus = {
  pending: 'pending',
  ready: 'ready',
  failed: 'failed',
} as const;
