/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * client API
 * OpenAPI spec version: 0.1.0
 */
import type { AssetStatus } from './assetStatus';

export interface AudioAssetOut {
  id: number;
  status: AssetStatus;
  mimeType: string;
  sizeBytes: number;
  fileKey: string;
  url: string;
}
