/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * client API
 * OpenAPI spec version: 0.1.0
 */

export const CategoryFinishInfoValue = {
  type: 'category_finish',
} as const;
export type CategoryFinishInfo = typeof CategoryFinishInfoValue;
