/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * client API
 * OpenAPI spec version: 0.1.0
 */
import type { LevelOutBase } from './levelOutBase';

export interface CategoryOut {
  id: number;
  name: string;
  currentLevel: LevelOutBase;
}
