/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * client API
 * OpenAPI spec version: 0.1.0
 */
import type { TargetLanguageCode } from './targetLanguageCode';
import type { CategoryOutBaseImage } from './categoryOutBaseImage';

export interface CategoryOutBase {
  id: number;
  name: string;
  language: TargetLanguageCode;
  image?: CategoryOutBaseImage;
}
