/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * client API
 * OpenAPI spec version: 0.1.0
 */

export type DefinitionGroup = typeof DefinitionGroup[keyof typeof DefinitionGroup];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DefinitionGroup = {
  VERB: 'VERB',
  NOUN: 'NOUN',
  DESCRIPTION: 'DESCRIPTION',
  PHRASE: 'PHRASE',
  ILLUSTRATION: 'ILLUSTRATION',
} as const;
