/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * client API
 * OpenAPI spec version: 0.1.0
 */

export type GetTranslateParams = {
/**
 * text to translate
 */
text: string;
/**
 * source language code
 */
lang_from: string;
/**
 * target language code
 */
lang_to: string;
};
