/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * client API
 * OpenAPI spec version: 0.1.0
 */
import type { AssetOut } from './assetOut';

export interface ImageDefinitionOut {
  id: number;
  type?: 'image';
  imageId: number;
  image: AssetOut;
}
