/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * client API
 * OpenAPI spec version: 0.1.0
 */
import type { TargetLanguageCode } from './targetLanguageCode';
import type { ImageAssetOut } from './imageAssetOut';

export interface ImageDefinitionOut {
  id: number;
  type: 'image';
  text: string;
  language: TargetLanguageCode;
  imageId: number;
  image: ImageAssetOut;
}
