/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * client API
 * OpenAPI spec version: 0.1.0
 */
import type { AssetStatus } from './assetStatus';
import type { ImageAssetOutWidth } from './imageAssetOutWidth';
import type { ImageAssetOutHeight } from './imageAssetOutHeight';

export interface ImageAssetOut {
  id: number;
  status: AssetStatus;
  mimeType: string;
  sizeBytes: number;
  alt: string;
  width?: ImageAssetOutWidth;
  height?: ImageAssetOutHeight;
  fileKey: string;
  url: string;
}
