/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * client API
 * OpenAPI spec version: 0.1.0
 */
import type { InterfaceLanguageOut } from './interfaceLanguageOut';

export interface InterfaceLanguageListResponse {
  items: InterfaceLanguageOut[];
}
