/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * client API
 * OpenAPI spec version: 0.1.0
 */

export type InterfaceLanguageCode = typeof InterfaceLanguageCode[keyof typeof InterfaceLanguageCode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InterfaceLanguageCode = {
  EN: 'EN',
  RU: 'RU',
  ES: 'ES',
  FR: 'FR',
  IT: 'IT',
} as const;
