/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * client API
 * OpenAPI spec version: 0.1.0
 */

export type IssueTypeName = typeof IssueTypeName[keyof typeof IssueTypeName];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IssueTypeName = {
  TYPO: 'TYPO',
  AMBIGUITY: 'AMBIGUITY',
  WRONG_TRANSLATION: 'WRONG_TRANSLATION',
  POOR_AUDIO: 'POOR_AUDIO',
  DISLIKE: 'DISLIKE',
  OTHER: 'OTHER',
} as const;
