/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * client API
 * OpenAPI spec version: 0.1.0
 */
import type { IssueOutText } from './issueOutText';
import type { IssueOutDecision } from './issueOutDecision';
import type { IssueStatusName } from './issueStatusName';
import type { IssueTypeName } from './issueTypeName';

export interface IssueOut {
  id: number;
  text?: IssueOutText;
  decision?: IssueOutDecision;
  status: IssueStatusName;
  type: IssueTypeName;
  meaning: string;
  definitions: string[];
}
