/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * client API
 * OpenAPI spec version: 0.1.0
 */
import type { IssueOutText } from './issueOutText';
import type { IssueOutStatus } from './issueOutStatus';
import type { IssueOutType } from './issueOutType';

export interface IssueOut {
  id: number;
  text?: IssueOutText;
  status?: IssueOutStatus;
  type?: IssueOutType;
  meaning: string;
  definitions: string[];
}
