/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * client API
 * OpenAPI spec version: 0.1.0
 */
import type { IssueCreateText } from './issueCreateText';
import type { IssueTypeName } from './issueTypeName';
import type { IssueCreateStatusId } from './issueCreateStatusId';
import type { IssueCreateReporterId } from './issueCreateReporterId';

export interface IssueCreate {
  text?: IssueCreateText;
  type: IssueTypeName;
  statusId?: IssueCreateStatusId;
  reporterId?: IssueCreateReporterId;
  questionId: number;
  meaning: string;
  definitions: string[];
}
