/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * client API
 * OpenAPI spec version: 0.1.0
 */

export type IssueStatusName = typeof IssueStatusName[keyof typeof IssueStatusName];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IssueStatusName = {
  NEW: 'NEW',
  IN_PROGRESS: 'IN_PROGRESS',
  RESOLVED: 'RESOLVED',
  DECLINED: 'DECLINED',
} as const;
