/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * client API
 * OpenAPI spec version: 0.1.0
 */

export interface LevelOutBase {
  id: number;
  name: string;
  alias: string;
  value: number;
}
