/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * client API
 * OpenAPI spec version: 0.1.0
 */
import type { TargetLanguageCode } from './targetLanguageCode';

export interface LevelOut {
  id: number;
  name: string;
  alias: string;
  value: number;
  language: TargetLanguageCode;
  currentScore: number;
  maxScore: number;
  isActive: boolean;
}
