/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * client API
 * OpenAPI spec version: 0.1.0
 */
import type { LevelUpInfo } from './levelUpInfo';
import type { CategoryFinishInfo } from './categoryFinishInfo';

export type QuestionUpdateOutInfoAnyOf = LevelUpInfo | CategoryFinishInfo;
