/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * client API
 * OpenAPI spec version: 0.1.0
 */
import type { QuestionTypeName } from './questionTypeName';
import type { MeaningOut } from './meaningOut';
import type { QuestionOutDefinitionsItem } from './questionOutDefinitionsItem';

export interface QuestionOut {
  id: number;
  type: QuestionTypeName;
  meaning: MeaningOut;
  definitions: QuestionOutDefinitionsItem[];
}
