/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * client API
 * OpenAPI spec version: 0.1.0
 */

export type QuestionTypeName = typeof QuestionTypeName[keyof typeof QuestionTypeName];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const QuestionTypeName = {
  text: 'text',
  image: 'image',
} as const;
