/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * client API
 * OpenAPI spec version: 0.1.0
 */

export type ReadLevelsLevelsGetParams = {
/**
 * Category ID
 */
category_id?: number;
};
