/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * client API
 * OpenAPI spec version: 0.1.0
 */
import type { SettingsInterfaceLangUpdateInterfaceLang } from './settingsInterfaceLangUpdateInterfaceLang';
import type { SettingsInterfaceLangUpdateTargetLanguage } from './settingsInterfaceLangUpdateTargetLanguage';

export interface SettingsInterfaceLangUpdate {
  interfaceLang: SettingsInterfaceLangUpdateInterfaceLang;
  targetLanguage?: SettingsInterfaceLangUpdateTargetLanguage;
}
