/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * client API
 * OpenAPI spec version: 0.1.0
 */
import type { SettingsTargetLanguageUpdateInterfaceLang } from './settingsTargetLanguageUpdateInterfaceLang';
import type { TargetLanguageCode } from './targetLanguageCode';

export interface SettingsTargetLanguageUpdate {
  interfaceLang?: SettingsTargetLanguageUpdateInterfaceLang;
  targetLanguage: TargetLanguageCode;
}
