/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * client API
 * OpenAPI spec version: 0.1.0
 */

export type SettingsInterfaceLangUpdateInterfaceLang = typeof SettingsInterfaceLangUpdateInterfaceLang[keyof typeof SettingsInterfaceLangUpdateInterfaceLang];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SettingsInterfaceLangUpdateInterfaceLang = {
  en: 'en',
  ru: 'ru',
  es: 'es',
  fr: 'fr',
  it: 'it',
} as const;
