/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * client API
 * OpenAPI spec version: 0.1.0
 */

export type TargetLanguageCode = typeof TargetLanguageCode[keyof typeof TargetLanguageCode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TargetLanguageCode = {
  EN: 'EN',
  ES: 'ES',
  RU: 'RU',
} as const;
