/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * client API
 * OpenAPI spec version: 0.1.0
 */

export type TranslateTextTranslateGetParams = {
/**
 * text to translate
 */
text: string;
context?: string | null;
};
