/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * client API
 * OpenAPI spec version: 0.1.0
 */
import type { UserOutName } from './userOutName';
import type { TargetLanguageCode } from './targetLanguageCode';
import type { UserRole } from './userRole';

export interface UserOut {
  id: number;
  email: string;
  name?: UserOutName;
  interfaceLang: string;
  targetLanguage: TargetLanguageCode;
  role: UserRole;
}
