name: Deploy client image

on:
  push:
    branches:
      - master

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: vitalyionov
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: true
          target: prod
          tags: |
            ghcr.io/vitalyionov/learn-language-client:latest
            ghcr.io/vitalyionov/learn-language-client:${{ github.sha }}
          build-args: |
            BASENAME=/client
            VITE_API_URL=/api/v1/client
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /opt/learn-language
            echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u vitalyionov --password-stdin
            CLIENT_IMAGE_TAG=${{ github.sha }} docker compose -f docker-compose.yml -f docker-compose.prod.yml pull client
            CLIENT_IMAGE_TAG=${{ github.sha }} docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d client --no-deps --force-recreate
            docker system prune -f

      - name: Telegram notify
        if: ${{ always() }}
        uses: appleboy/telegram-action@v1.0.1
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdown
          disable_web_page_preview: true
          message: |
            ${{ job.status == 'success' && '✅' || '❌' }} Deploy *${{ job.status }}* for *${{ github.repository }}*
            *Branch:* ${{ github.ref_name }}
            *Commit:* ${{ github.sha }}
            [Action](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
