/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * client API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CategoriesListResponse,
  CategoriesProgressListResponse,
  CategoryOut,
  GetLevelsListParams,
  GetTranslateParams,
  HTTPValidationError,
  InterfaceLanguageListResponse,
  IssueCreate,
  IssueOut,
  IssueTypeListResponse,
  IssuesListResponse,
  LevelsListResponse,
  ProgressByUserStatistic,
  QuestionGenerate,
  QuestionOut,
  QuestionUpdate,
  QuestionUpdateOut,
  SettingsInterfaceLangUpdate,
  SettingsTargetLanguageUpdate,
  TargetLanguageListResponse,
  TodayScoreStatistic,
  TranslateOut,
  UserOut
} from './client-schemas';

import { clientRequest } from '../shared/lib/apiClient/apiClient';
/**
 * @summary Read User
 */
export const getCurrentUser = (
    
 signal?: AbortSignal
) => {
      
      
      return clientRequest<UserOut>(
      {url: `/current_user`, method: 'GET', signal
    },
      );
    }
  

export const getGetCurrentUserQueryKey = () => {
    return [`/current_user`] as const;
    }

    
export const getGetCurrentUserQueryOptions = <TData = Awaited<ReturnType<typeof getCurrentUser>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCurrentUserQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCurrentUser>>> = ({ signal }) => getCurrentUser(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCurrentUserQueryResult = NonNullable<Awaited<ReturnType<typeof getCurrentUser>>>
export type GetCurrentUserQueryError = unknown


export function useGetCurrentUser<TData = Awaited<ReturnType<typeof getCurrentUser>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCurrentUser>>,
          TError,
          Awaited<ReturnType<typeof getCurrentUser>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCurrentUser<TData = Awaited<ReturnType<typeof getCurrentUser>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCurrentUser>>,
          TError,
          Awaited<ReturnType<typeof getCurrentUser>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCurrentUser<TData = Awaited<ReturnType<typeof getCurrentUser>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Read User
 */

export function useGetCurrentUser<TData = Awaited<ReturnType<typeof getCurrentUser>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCurrentUserQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Read Category
 */
export const getCategory = (
    categoryId: number,
 signal?: AbortSignal
) => {
      
      
      return clientRequest<CategoryOut>(
      {url: `/categories/${categoryId}`, method: 'GET', signal
    },
      );
    }
  

export const getGetCategoryQueryKey = (categoryId: number,) => {
    return [`/categories/${categoryId}`] as const;
    }

    
export const getGetCategoryQueryOptions = <TData = Awaited<ReturnType<typeof getCategory>>, TError = HTTPValidationError>(categoryId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCategory>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCategoryQueryKey(categoryId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCategory>>> = ({ signal }) => getCategory(categoryId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(categoryId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCategory>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCategoryQueryResult = NonNullable<Awaited<ReturnType<typeof getCategory>>>
export type GetCategoryQueryError = HTTPValidationError


export function useGetCategory<TData = Awaited<ReturnType<typeof getCategory>>, TError = HTTPValidationError>(
 categoryId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCategory>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCategory>>,
          TError,
          Awaited<ReturnType<typeof getCategory>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCategory<TData = Awaited<ReturnType<typeof getCategory>>, TError = HTTPValidationError>(
 categoryId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCategory>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCategory>>,
          TError,
          Awaited<ReturnType<typeof getCategory>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCategory<TData = Awaited<ReturnType<typeof getCategory>>, TError = HTTPValidationError>(
 categoryId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCategory>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Read Category
 */

export function useGetCategory<TData = Awaited<ReturnType<typeof getCategory>>, TError = HTTPValidationError>(
 categoryId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCategory>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCategoryQueryOptions(categoryId,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Read Categories
 */
export const getCategoriesList = (
    
 signal?: AbortSignal
) => {
      
      
      return clientRequest<CategoriesListResponse>(
      {url: `/categories`, method: 'GET', signal
    },
      );
    }
  

export const getGetCategoriesListQueryKey = () => {
    return [`/categories`] as const;
    }

    
export const getGetCategoriesListQueryOptions = <TData = Awaited<ReturnType<typeof getCategoriesList>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCategoriesList>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCategoriesListQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCategoriesList>>> = ({ signal }) => getCategoriesList(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCategoriesList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCategoriesListQueryResult = NonNullable<Awaited<ReturnType<typeof getCategoriesList>>>
export type GetCategoriesListQueryError = unknown


export function useGetCategoriesList<TData = Awaited<ReturnType<typeof getCategoriesList>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCategoriesList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCategoriesList>>,
          TError,
          Awaited<ReturnType<typeof getCategoriesList>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCategoriesList<TData = Awaited<ReturnType<typeof getCategoriesList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCategoriesList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCategoriesList>>,
          TError,
          Awaited<ReturnType<typeof getCategoriesList>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCategoriesList<TData = Awaited<ReturnType<typeof getCategoriesList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCategoriesList>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Read Categories
 */

export function useGetCategoriesList<TData = Awaited<ReturnType<typeof getCategoriesList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCategoriesList>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCategoriesListQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Read Levels
 */
export const getLevelsList = (
    params?: GetLevelsListParams,
 signal?: AbortSignal
) => {
      
      
      return clientRequest<LevelsListResponse>(
      {url: `/levels`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getGetLevelsListQueryKey = (params?: GetLevelsListParams,) => {
    return [`/levels`, ...(params ? [params]: [])] as const;
    }

    
export const getGetLevelsListQueryOptions = <TData = Awaited<ReturnType<typeof getLevelsList>>, TError = HTTPValidationError>(params?: GetLevelsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLevelsList>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLevelsListQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLevelsList>>> = ({ signal }) => getLevelsList(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLevelsList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetLevelsListQueryResult = NonNullable<Awaited<ReturnType<typeof getLevelsList>>>
export type GetLevelsListQueryError = HTTPValidationError


export function useGetLevelsList<TData = Awaited<ReturnType<typeof getLevelsList>>, TError = HTTPValidationError>(
 params: undefined |  GetLevelsListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLevelsList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLevelsList>>,
          TError,
          Awaited<ReturnType<typeof getLevelsList>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLevelsList<TData = Awaited<ReturnType<typeof getLevelsList>>, TError = HTTPValidationError>(
 params?: GetLevelsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLevelsList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLevelsList>>,
          TError,
          Awaited<ReturnType<typeof getLevelsList>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLevelsList<TData = Awaited<ReturnType<typeof getLevelsList>>, TError = HTTPValidationError>(
 params?: GetLevelsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLevelsList>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Read Levels
 */

export function useGetLevelsList<TData = Awaited<ReturnType<typeof getLevelsList>>, TError = HTTPValidationError>(
 params?: GetLevelsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLevelsList>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetLevelsListQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Translate Text
 */
export const getTranslate = (
    params: GetTranslateParams,
 signal?: AbortSignal
) => {
      
      
      return clientRequest<TranslateOut>(
      {url: `/translate`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getGetTranslateQueryKey = (params: GetTranslateParams,) => {
    return [`/translate`, ...(params ? [params]: [])] as const;
    }

    
export const getGetTranslateQueryOptions = <TData = Awaited<ReturnType<typeof getTranslate>>, TError = HTTPValidationError>(params: GetTranslateParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTranslate>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTranslateQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTranslate>>> = ({ signal }) => getTranslate(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTranslate>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTranslateQueryResult = NonNullable<Awaited<ReturnType<typeof getTranslate>>>
export type GetTranslateQueryError = HTTPValidationError


export function useGetTranslate<TData = Awaited<ReturnType<typeof getTranslate>>, TError = HTTPValidationError>(
 params: GetTranslateParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTranslate>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTranslate>>,
          TError,
          Awaited<ReturnType<typeof getTranslate>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTranslate<TData = Awaited<ReturnType<typeof getTranslate>>, TError = HTTPValidationError>(
 params: GetTranslateParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTranslate>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTranslate>>,
          TError,
          Awaited<ReturnType<typeof getTranslate>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTranslate<TData = Awaited<ReturnType<typeof getTranslate>>, TError = HTTPValidationError>(
 params: GetTranslateParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTranslate>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Translate Text
 */

export function useGetTranslate<TData = Awaited<ReturnType<typeof getTranslate>>, TError = HTTPValidationError>(
 params: GetTranslateParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTranslate>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTranslateQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Generate Question
 */
export const generateQuestion = (
    questionGenerate: QuestionGenerate,
 signal?: AbortSignal
) => {
      
      
      return clientRequest<QuestionOut>(
      {url: `/questions/generate`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: questionGenerate, signal
    },
      );
    }
  


export const getGenerateQuestionMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof generateQuestion>>, TError,{data: QuestionGenerate}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof generateQuestion>>, TError,{data: QuestionGenerate}, TContext> => {

const mutationKey = ['generateQuestion'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof generateQuestion>>, {data: QuestionGenerate}> = (props) => {
          const {data} = props ?? {};

          return  generateQuestion(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type GenerateQuestionMutationResult = NonNullable<Awaited<ReturnType<typeof generateQuestion>>>
    export type GenerateQuestionMutationBody = QuestionGenerate
    export type GenerateQuestionMutationError = HTTPValidationError

    /**
 * @summary Generate Question
 */
export const useGenerateQuestion = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof generateQuestion>>, TError,{data: QuestionGenerate}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof generateQuestion>>,
        TError,
        {data: QuestionGenerate},
        TContext
      > => {

      const mutationOptions = getGenerateQuestionMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * @summary Update Question Endpoint
 */
export const updateQuestion = (
    questionId: number,
    questionUpdate: QuestionUpdate,
 ) => {
      
      
      return clientRequest<QuestionUpdateOut>(
      {url: `/questions/${questionId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: questionUpdate
    },
      );
    }
  


export const getUpdateQuestionMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateQuestion>>, TError,{questionId: number;data: QuestionUpdate}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateQuestion>>, TError,{questionId: number;data: QuestionUpdate}, TContext> => {

const mutationKey = ['updateQuestion'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateQuestion>>, {questionId: number;data: QuestionUpdate}> = (props) => {
          const {questionId,data} = props ?? {};

          return  updateQuestion(questionId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateQuestionMutationResult = NonNullable<Awaited<ReturnType<typeof updateQuestion>>>
    export type UpdateQuestionMutationBody = QuestionUpdate
    export type UpdateQuestionMutationError = HTTPValidationError

    /**
 * @summary Update Question Endpoint
 */
export const useUpdateQuestion = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateQuestion>>, TError,{questionId: number;data: QuestionUpdate}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateQuestion>>,
        TError,
        {questionId: number;data: QuestionUpdate},
        TContext
      > => {

      const mutationOptions = getUpdateQuestionMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * @summary Get Progress By User
 */
export const getStatisticsProgress = (
    
 signal?: AbortSignal
) => {
      
      
      return clientRequest<ProgressByUserStatistic>(
      {url: `/statistics/progress/`, method: 'GET', signal
    },
      );
    }
  

export const getGetStatisticsProgressQueryKey = () => {
    return [`/statistics/progress/`] as const;
    }

    
export const getGetStatisticsProgressQueryOptions = <TData = Awaited<ReturnType<typeof getStatisticsProgress>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStatisticsProgress>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStatisticsProgressQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStatisticsProgress>>> = ({ signal }) => getStatisticsProgress(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getStatisticsProgress>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetStatisticsProgressQueryResult = NonNullable<Awaited<ReturnType<typeof getStatisticsProgress>>>
export type GetStatisticsProgressQueryError = unknown


export function useGetStatisticsProgress<TData = Awaited<ReturnType<typeof getStatisticsProgress>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStatisticsProgress>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStatisticsProgress>>,
          TError,
          Awaited<ReturnType<typeof getStatisticsProgress>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStatisticsProgress<TData = Awaited<ReturnType<typeof getStatisticsProgress>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStatisticsProgress>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStatisticsProgress>>,
          TError,
          Awaited<ReturnType<typeof getStatisticsProgress>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStatisticsProgress<TData = Awaited<ReturnType<typeof getStatisticsProgress>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStatisticsProgress>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Progress By User
 */

export function useGetStatisticsProgress<TData = Awaited<ReturnType<typeof getStatisticsProgress>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStatisticsProgress>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetStatisticsProgressQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Get Today Progress By User
 */
export const getStatisticsTodayProgress = (
    
 signal?: AbortSignal
) => {
      
      
      return clientRequest<ProgressByUserStatistic>(
      {url: `/statistics/today_progress/`, method: 'GET', signal
    },
      );
    }
  

export const getGetStatisticsTodayProgressQueryKey = () => {
    return [`/statistics/today_progress/`] as const;
    }

    
export const getGetStatisticsTodayProgressQueryOptions = <TData = Awaited<ReturnType<typeof getStatisticsTodayProgress>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStatisticsTodayProgress>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStatisticsTodayProgressQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStatisticsTodayProgress>>> = ({ signal }) => getStatisticsTodayProgress(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getStatisticsTodayProgress>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetStatisticsTodayProgressQueryResult = NonNullable<Awaited<ReturnType<typeof getStatisticsTodayProgress>>>
export type GetStatisticsTodayProgressQueryError = unknown


export function useGetStatisticsTodayProgress<TData = Awaited<ReturnType<typeof getStatisticsTodayProgress>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStatisticsTodayProgress>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStatisticsTodayProgress>>,
          TError,
          Awaited<ReturnType<typeof getStatisticsTodayProgress>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStatisticsTodayProgress<TData = Awaited<ReturnType<typeof getStatisticsTodayProgress>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStatisticsTodayProgress>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStatisticsTodayProgress>>,
          TError,
          Awaited<ReturnType<typeof getStatisticsTodayProgress>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStatisticsTodayProgress<TData = Awaited<ReturnType<typeof getStatisticsTodayProgress>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStatisticsTodayProgress>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Today Progress By User
 */

export function useGetStatisticsTodayProgress<TData = Awaited<ReturnType<typeof getStatisticsTodayProgress>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStatisticsTodayProgress>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetStatisticsTodayProgressQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Get Today Score By User
 */
export const getStatisticsTodayScore = (
    
 signal?: AbortSignal
) => {
      
      
      return clientRequest<TodayScoreStatistic>(
      {url: `/statistics/today_score/`, method: 'GET', signal
    },
      );
    }
  

export const getGetStatisticsTodayScoreQueryKey = () => {
    return [`/statistics/today_score/`] as const;
    }

    
export const getGetStatisticsTodayScoreQueryOptions = <TData = Awaited<ReturnType<typeof getStatisticsTodayScore>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStatisticsTodayScore>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStatisticsTodayScoreQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStatisticsTodayScore>>> = ({ signal }) => getStatisticsTodayScore(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getStatisticsTodayScore>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetStatisticsTodayScoreQueryResult = NonNullable<Awaited<ReturnType<typeof getStatisticsTodayScore>>>
export type GetStatisticsTodayScoreQueryError = unknown


export function useGetStatisticsTodayScore<TData = Awaited<ReturnType<typeof getStatisticsTodayScore>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStatisticsTodayScore>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStatisticsTodayScore>>,
          TError,
          Awaited<ReturnType<typeof getStatisticsTodayScore>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStatisticsTodayScore<TData = Awaited<ReturnType<typeof getStatisticsTodayScore>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStatisticsTodayScore>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStatisticsTodayScore>>,
          TError,
          Awaited<ReturnType<typeof getStatisticsTodayScore>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStatisticsTodayScore<TData = Awaited<ReturnType<typeof getStatisticsTodayScore>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStatisticsTodayScore>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Today Score By User
 */

export function useGetStatisticsTodayScore<TData = Awaited<ReturnType<typeof getStatisticsTodayScore>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStatisticsTodayScore>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetStatisticsTodayScoreQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Get Categories Progress
 */
export const getStatisticsCategoriesProgress = (
    
 signal?: AbortSignal
) => {
      
      
      return clientRequest<CategoriesProgressListResponse>(
      {url: `/statistics/categories-progress/`, method: 'GET', signal
    },
      );
    }
  

export const getGetStatisticsCategoriesProgressQueryKey = () => {
    return [`/statistics/categories-progress/`] as const;
    }

    
export const getGetStatisticsCategoriesProgressQueryOptions = <TData = Awaited<ReturnType<typeof getStatisticsCategoriesProgress>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStatisticsCategoriesProgress>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStatisticsCategoriesProgressQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStatisticsCategoriesProgress>>> = ({ signal }) => getStatisticsCategoriesProgress(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getStatisticsCategoriesProgress>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetStatisticsCategoriesProgressQueryResult = NonNullable<Awaited<ReturnType<typeof getStatisticsCategoriesProgress>>>
export type GetStatisticsCategoriesProgressQueryError = unknown


export function useGetStatisticsCategoriesProgress<TData = Awaited<ReturnType<typeof getStatisticsCategoriesProgress>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStatisticsCategoriesProgress>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStatisticsCategoriesProgress>>,
          TError,
          Awaited<ReturnType<typeof getStatisticsCategoriesProgress>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStatisticsCategoriesProgress<TData = Awaited<ReturnType<typeof getStatisticsCategoriesProgress>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStatisticsCategoriesProgress>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStatisticsCategoriesProgress>>,
          TError,
          Awaited<ReturnType<typeof getStatisticsCategoriesProgress>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStatisticsCategoriesProgress<TData = Awaited<ReturnType<typeof getStatisticsCategoriesProgress>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStatisticsCategoriesProgress>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Categories Progress
 */

export function useGetStatisticsCategoriesProgress<TData = Awaited<ReturnType<typeof getStatisticsCategoriesProgress>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStatisticsCategoriesProgress>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetStatisticsCategoriesProgressQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Get Issue
 */
export const getIssuesList = (
    
 signal?: AbortSignal
) => {
      
      
      return clientRequest<IssuesListResponse>(
      {url: `/issues`, method: 'GET', signal
    },
      );
    }
  

export const getGetIssuesListQueryKey = () => {
    return [`/issues`] as const;
    }

    
export const getGetIssuesListQueryOptions = <TData = Awaited<ReturnType<typeof getIssuesList>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIssuesList>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetIssuesListQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getIssuesList>>> = ({ signal }) => getIssuesList(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getIssuesList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetIssuesListQueryResult = NonNullable<Awaited<ReturnType<typeof getIssuesList>>>
export type GetIssuesListQueryError = unknown


export function useGetIssuesList<TData = Awaited<ReturnType<typeof getIssuesList>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIssuesList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getIssuesList>>,
          TError,
          Awaited<ReturnType<typeof getIssuesList>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetIssuesList<TData = Awaited<ReturnType<typeof getIssuesList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIssuesList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getIssuesList>>,
          TError,
          Awaited<ReturnType<typeof getIssuesList>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetIssuesList<TData = Awaited<ReturnType<typeof getIssuesList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIssuesList>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Issue
 */

export function useGetIssuesList<TData = Awaited<ReturnType<typeof getIssuesList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIssuesList>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetIssuesListQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Add Issue
 */
export const createIssue = (
    issueCreate: IssueCreate,
 signal?: AbortSignal
) => {
      
      
      return clientRequest<IssueOut>(
      {url: `/issues`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: issueCreate, signal
    },
      );
    }
  


export const getCreateIssueMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createIssue>>, TError,{data: IssueCreate}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createIssue>>, TError,{data: IssueCreate}, TContext> => {

const mutationKey = ['createIssue'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createIssue>>, {data: IssueCreate}> = (props) => {
          const {data} = props ?? {};

          return  createIssue(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateIssueMutationResult = NonNullable<Awaited<ReturnType<typeof createIssue>>>
    export type CreateIssueMutationBody = IssueCreate
    export type CreateIssueMutationError = HTTPValidationError

    /**
 * @summary Add Issue
 */
export const useCreateIssue = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createIssue>>, TError,{data: IssueCreate}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createIssue>>,
        TError,
        {data: IssueCreate},
        TContext
      > => {

      const mutationOptions = getCreateIssueMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * @summary Get Issue Types
 */
export const getIssueTypesList = (
    
 signal?: AbortSignal
) => {
      
      
      return clientRequest<IssueTypeListResponse>(
      {url: `/issue_types`, method: 'GET', signal
    },
      );
    }
  

export const getGetIssueTypesListQueryKey = () => {
    return [`/issue_types`] as const;
    }

    
export const getGetIssueTypesListQueryOptions = <TData = Awaited<ReturnType<typeof getIssueTypesList>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIssueTypesList>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetIssueTypesListQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getIssueTypesList>>> = ({ signal }) => getIssueTypesList(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getIssueTypesList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetIssueTypesListQueryResult = NonNullable<Awaited<ReturnType<typeof getIssueTypesList>>>
export type GetIssueTypesListQueryError = unknown


export function useGetIssueTypesList<TData = Awaited<ReturnType<typeof getIssueTypesList>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIssueTypesList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getIssueTypesList>>,
          TError,
          Awaited<ReturnType<typeof getIssueTypesList>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetIssueTypesList<TData = Awaited<ReturnType<typeof getIssueTypesList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIssueTypesList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getIssueTypesList>>,
          TError,
          Awaited<ReturnType<typeof getIssueTypesList>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetIssueTypesList<TData = Awaited<ReturnType<typeof getIssueTypesList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIssueTypesList>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Issue Types
 */

export function useGetIssueTypesList<TData = Awaited<ReturnType<typeof getIssueTypesList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIssueTypesList>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetIssueTypesListQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Update Interface Language
 */
export const updateSettingsInterfaceLanguage = (
    settingsInterfaceLangUpdate: SettingsInterfaceLangUpdate,
 ) => {
      
      
      return clientRequest<boolean>(
      {url: `/settings/interface-lang`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: settingsInterfaceLangUpdate
    },
      );
    }
  


export const getUpdateSettingsInterfaceLanguageMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateSettingsInterfaceLanguage>>, TError,{data: SettingsInterfaceLangUpdate}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateSettingsInterfaceLanguage>>, TError,{data: SettingsInterfaceLangUpdate}, TContext> => {

const mutationKey = ['updateSettingsInterfaceLanguage'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateSettingsInterfaceLanguage>>, {data: SettingsInterfaceLangUpdate}> = (props) => {
          const {data} = props ?? {};

          return  updateSettingsInterfaceLanguage(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateSettingsInterfaceLanguageMutationResult = NonNullable<Awaited<ReturnType<typeof updateSettingsInterfaceLanguage>>>
    export type UpdateSettingsInterfaceLanguageMutationBody = SettingsInterfaceLangUpdate
    export type UpdateSettingsInterfaceLanguageMutationError = HTTPValidationError

    /**
 * @summary Update Interface Language
 */
export const useUpdateSettingsInterfaceLanguage = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateSettingsInterfaceLanguage>>, TError,{data: SettingsInterfaceLangUpdate}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateSettingsInterfaceLanguage>>,
        TError,
        {data: SettingsInterfaceLangUpdate},
        TContext
      > => {

      const mutationOptions = getUpdateSettingsInterfaceLanguageMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * @summary Update Target Language
 */
export const updateSettingsTargetLanguage = (
    settingsTargetLanguageUpdate: SettingsTargetLanguageUpdate,
 ) => {
      
      
      return clientRequest<boolean>(
      {url: `/settings/target-language`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: settingsTargetLanguageUpdate
    },
      );
    }
  


export const getUpdateSettingsTargetLanguageMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateSettingsTargetLanguage>>, TError,{data: SettingsTargetLanguageUpdate}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateSettingsTargetLanguage>>, TError,{data: SettingsTargetLanguageUpdate}, TContext> => {

const mutationKey = ['updateSettingsTargetLanguage'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateSettingsTargetLanguage>>, {data: SettingsTargetLanguageUpdate}> = (props) => {
          const {data} = props ?? {};

          return  updateSettingsTargetLanguage(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateSettingsTargetLanguageMutationResult = NonNullable<Awaited<ReturnType<typeof updateSettingsTargetLanguage>>>
    export type UpdateSettingsTargetLanguageMutationBody = SettingsTargetLanguageUpdate
    export type UpdateSettingsTargetLanguageMutationError = HTTPValidationError

    /**
 * @summary Update Target Language
 */
export const useUpdateSettingsTargetLanguage = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateSettingsTargetLanguage>>, TError,{data: SettingsTargetLanguageUpdate}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateSettingsTargetLanguage>>,
        TError,
        {data: SettingsTargetLanguageUpdate},
        TContext
      > => {

      const mutationOptions = getUpdateSettingsTargetLanguageMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * @summary Get Target Languages
 */
export const getTargetLanguagesList = (
    
 signal?: AbortSignal
) => {
      
      
      return clientRequest<TargetLanguageListResponse>(
      {url: `/target-languages`, method: 'GET', signal
    },
      );
    }
  

export const getGetTargetLanguagesListQueryKey = () => {
    return [`/target-languages`] as const;
    }

    
export const getGetTargetLanguagesListQueryOptions = <TData = Awaited<ReturnType<typeof getTargetLanguagesList>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTargetLanguagesList>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTargetLanguagesListQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTargetLanguagesList>>> = ({ signal }) => getTargetLanguagesList(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTargetLanguagesList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTargetLanguagesListQueryResult = NonNullable<Awaited<ReturnType<typeof getTargetLanguagesList>>>
export type GetTargetLanguagesListQueryError = unknown


export function useGetTargetLanguagesList<TData = Awaited<ReturnType<typeof getTargetLanguagesList>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTargetLanguagesList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTargetLanguagesList>>,
          TError,
          Awaited<ReturnType<typeof getTargetLanguagesList>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTargetLanguagesList<TData = Awaited<ReturnType<typeof getTargetLanguagesList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTargetLanguagesList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTargetLanguagesList>>,
          TError,
          Awaited<ReturnType<typeof getTargetLanguagesList>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTargetLanguagesList<TData = Awaited<ReturnType<typeof getTargetLanguagesList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTargetLanguagesList>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Target Languages
 */

export function useGetTargetLanguagesList<TData = Awaited<ReturnType<typeof getTargetLanguagesList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTargetLanguagesList>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTargetLanguagesListQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Get Interface Languages
 */
export const getInterfaceLanguagesList = (
    
 signal?: AbortSignal
) => {
      
      
      return clientRequest<InterfaceLanguageListResponse>(
      {url: `/interface-languages`, method: 'GET', signal
    },
      );
    }
  

export const getGetInterfaceLanguagesListQueryKey = () => {
    return [`/interface-languages`] as const;
    }

    
export const getGetInterfaceLanguagesListQueryOptions = <TData = Awaited<ReturnType<typeof getInterfaceLanguagesList>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInterfaceLanguagesList>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetInterfaceLanguagesListQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getInterfaceLanguagesList>>> = ({ signal }) => getInterfaceLanguagesList(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getInterfaceLanguagesList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetInterfaceLanguagesListQueryResult = NonNullable<Awaited<ReturnType<typeof getInterfaceLanguagesList>>>
export type GetInterfaceLanguagesListQueryError = unknown


export function useGetInterfaceLanguagesList<TData = Awaited<ReturnType<typeof getInterfaceLanguagesList>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInterfaceLanguagesList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getInterfaceLanguagesList>>,
          TError,
          Awaited<ReturnType<typeof getInterfaceLanguagesList>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetInterfaceLanguagesList<TData = Awaited<ReturnType<typeof getInterfaceLanguagesList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInterfaceLanguagesList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getInterfaceLanguagesList>>,
          TError,
          Awaited<ReturnType<typeof getInterfaceLanguagesList>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetInterfaceLanguagesList<TData = Awaited<ReturnType<typeof getInterfaceLanguagesList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInterfaceLanguagesList>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Interface Languages
 */

export function useGetInterfaceLanguagesList<TData = Awaited<ReturnType<typeof getInterfaceLanguagesList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInterfaceLanguagesList>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetInterfaceLanguagesListQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}
